# progress bar {bar}

bar-format: "&8[{value}&8]"

task-time: 1

lang:
  format: "&cCzas &f{time} &7 |  {bar}"
  sub-title: "&a{value}%"
  title: "&7"

styles:
  char: "I"
  size: 100
  no-active: "&7"
  active: "&a"

sec: ' {sec}s'
min: ' {min}m'
hour: ' {hour}h'
day: '{day}d'


format: "{d}{h}{m}{s}"

